
import AboutContent from "@/components/AboutContent";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Rohama | About Me",
  description: "Generated by create next app",
};
const About = () => {
  return (
    <AboutContent />
  );
};

export default About;
