
import type { Metadata } from "next";
import AboutContent from "@/components/AboutContent";

export const metadata: Metadata = {
  title: "Rohama | About",
  description: "Generated by create next app",
};
const AboutPage = () => {
  return (
  <AboutContent />
  );
};

export default AboutPage;
