import React from 'react'
import type { Metadata } from "next";
import ExperienceContent from '@/components/ExperienceContent';

export const metadata: Metadata = {
  title: "Rohama | Experience",
  description: "Generated by create next app",
};
const ExperiencePage = () => {
  return (
    <ExperienceContent/>
  )
}

export default ExperiencePage