
import ProjectsContent from "@/components/ProjectsContent";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Rohama | Projects",
  description: "Generated by create next app",
};
const ProjectsPage = () => {
  

  return (
  <ProjectsContent />
  );
};

export default ProjectsPage;
