
import ContactContent from "@/components/ContactContent";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Rohama | Contact",
  description: "Generated by create next app",
};
const Contact = () => {
  return (
    <ContactContent />
  );
};

export default Contact;
