import SkillsContent from "@/components/SkillsContent";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Rohama | Skills",
  description: "Generated by create next app",
};

const Skills = () => {
  return <SkillsContent />;
};

export default Skills;
