
import ResumeContent from "@/components/ResumeContent";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Rohama | Resume",
  description: "Generated by create next app",
};
const resumeData = [
  {
    year: "2019 - 2020",
    title: "Matriculation",
    desc: "Muslim Green Public School, M.Garh",
  },
  {
    year: "2020 - 2022",
    title: "Intermediate",
    desc: "Govt Degree College, M.Garh",
  },
  {
    year: "2022 - 2026",
    title: "Software Engineering, Graduation",
    desc: "UET, Taxila",
  },
];

const ResumePage = () => {
  return (
   <ResumeContent/>
  );
};

export default ResumePage;
